
PACKAGENAME := tyxml
LIBNAME     := tyxml

## Binaries

OCAMLFIND := ocamlfind
OCAMLLEX  := ocamllex

OCAMLDUCEFIND := ocamlducefind

## Build options

OCAMLDUCE  :=YES
NATDYNLINK :=YES

# DBG := -g

OBJEXT := .o
LIBEXT := .a

