
PACKAGENAME := tyxml
LIBNAME     := tyxml

## Binaries

OCAMLFIND := ocamlfind
OCAMLLEX  := ocamllex

OCAMLDUCEFIND := ocamlducefind

## Build options

## Shall we build ocamlduce support ? [detect]
OCAMLDUCE := \
 $(shell (${OCAMLDUCEFIND} query  > /dev/null 2>&1 && echo yes) || echo no)

## Shall we build native plugins ? [detect]
NATDYNLINK := \
  $(shell (test -f $$(${OCAMLFIND} query dynlink)/dynlink.cmxa && echo yes) || echo no)

# DBG := -g

OBJEXT := .o
LIBEXT := .a

